//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYCHARITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharitablePlace
    {
        public int PID { get; set; }
        public string Pname { get; set; }
        public string RequestedOrgName { get; set; }
        public Nullable<System.DateTime> RequestStartDate { get; set; }
        public Nullable<System.DateTime> RequestEndDate { get; set; }
        public string Addresss { get; set; }
        public string Placelat { get; set; }
        public string Placelong { get; set; }
        public string Description { get; set; }
        public string image { get; set; }
    }
}
