//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYCHARITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int DonationID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string OrgName { get; set; }
        public Nullable<int> DonateAmount { get; set; }
        public Nullable<System.DateTime> DonateDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
