//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYCHARITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int VID { get; set; }
        public string UserID { get; set; }
        public string VName { get; set; }
        public string VEmail { get; set; }
        public string VGender { get; set; }
        public string VPreferType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
